# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TartApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TartApp
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  
  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/MLVision'
  # If using an on-device API:
  pod 'Firebase/MLVisionTextModel'
  pod 'Firebase/MLVisionAutoML'
  pod 'Firebase/MLVisionObjectDetection'
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVisionFaceModel'
  pod 'Firebase/MLVisionLabelModel'
  
  
  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Parse'

  target 'TartAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TartAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
